### ISSUE TITLE
Javascript error in examples on huggingface that use jupyter-widgets

### ISSUE THREAD

**Issue by hubertus65** [voila-dashboards/voila-huggingface#3]
## Description

I get the following error message when open the bqplot example from the link to huggingface: [bqplot](https://voila-dashboards-voila-huggingface.hf.space/voila/render/bqplot.ipynb?)

Failed to load view class 'ErrorWidgetView' from module '@jupyter-widgets/base'
Error: No version of module @jupyter-widgets/base is registered
    at _.loadClass (https://voila-dashboards-voila-huggingface.hf.space/voila/static/7018.voila.js:1:77776)
    at _.loadViewClass (https://voila-dashboards-voila-huggingface.hf.space/voila/static/7018.voila.js:1:74931)
    at https://voila-dashboards-voila-huggingface.hf.space/voila/static/7018.voila.js:1:66785
    at async g.renderModel (https://voila-dashboards-voila-huggingface.hf.space/voila/static/7018.voila.js:1:65329)

## Reproduce

1. Open the link above.
2. Click on 'Click to show javascript-error'
3. you can see the error text above directly

## Expected behavior

No error message. The fancy plot that should be there, which I have never seen before. 

## Context

The link to the hugging face examples in the readme to the voola-huggingspace page.

- voila version 
- Operating System and version: Windows 11
- Browser and version: Latest updated Chrome as of 3/22/2024

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `voila` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by feddernico** [comment]
I hmam experiencing the same error and so far I managed just to circumvent it by using the **HTML** component instead of ipywidgets and update the code accordingly.

For example the basics.ipynb notebook becomes:

```{python}

from IPython.display import HTML

HTML("""
<div>
    <label for="slider">x: </label>
    <input type="range" id="slider" min="0" max="10" step="0.1" value="4">
    <br><br>
    <label for="output">x²: </label>
    <input type="text" id="output" value="16" disabled>
</div>

<script>
document.getElementById("slider").addEventListener("input", function() {
    let x = parseFloat(this.value);
    document.getElementById("output").value = (x * x).toFixed(2);
});
</script>
""")
```

**Comment by trungleduc** [comment]
Hi. Thank for reporting, it's fixed
